[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"

[tool.mypy]
show_error_codes = true
ignore_missing_imports = true
exclude = [
    'examples/',
    'src/plotting\.py',
]

[tool.ruff]
line-length = 90
exclude = [
  "virtenv/**"
]
