name: ci

on:
  push:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        # python-versions: [ "3.8", "3.9", "3.10" ]
        python-versions: [ "3.9" ]
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-versions }}

      - name: Install dependencies
        run: |
          # https://github.com/mbari-org/pypam-based-processing/actions/runs/4327554890/jobs/7556425585
          # maybe skip this for now:
          # sudo apt-get update && sudo apt-get upgrade -y
          
          sudo apt-get install libsndfile1
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: test
        run:
          python -m pytest

      - name: Check source formatting
        run:
          ruff format --check
      - name: Source code linting
        run:
          ruff check
